import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#E31D1C',
          light: '#F45B58',
          dark: '#B71918',
          soft: '#FFF1F1',
          bg: '#FFF7F7',
          alt: '#FFE7E7',
          border: '#FFD1D1',
          fg: '#FFFFFF',
        },
        blue: {
          DEFAULT: '#1784DA',
          light: '#4FB3EC',
          dark: '#005B96',
          soft: '#EEF7FF',
          border: '#C7E8FA',
        },
        accent: {
          DEFAULT: '#F7D428',
          soft: '#FFFBE5',
          border: '#F5E58A',
          text: '#705E00',
          fg: '#112641',
          red: '#E31D1C',
          gold: '#F7D428',
          goldSoft: '#FFFBE5',
        },
        surface: {
          page: '#F8FCFF',
          card: '#FFFFFF',
          alt: '#F3F8FC',
          tint: '#EEF7FF',
          inset: '#E8F4FB',
          navy: '#112641',
        },
        ntd: {
          primary: 'var(--ntd-primary, #4D97FF)',
          'primary-light': 'var(--ntd-primary-light, #80b3ff)',
          'primary-dark': 'var(--ntd-primary-dark, #0F3460)',
          'primary-soft': 'var(--ntd-primary-soft, #e8f4ff)',
          'primary-bg': 'var(--ntd-primary-bg, #f0f7ff)',
          'primary-alt': 'var(--ntd-primary-alt, #dbeeff)',
          'primary-border': 'var(--ntd-primary-border, #93c5fd)',
          'primary-fg': 'var(--ntd-primary-fg, #ffffff)',
          accent: 'var(--ntd-accent, #FCDC62)',
          'accent-soft': 'var(--ntd-accent-soft, #fffbeb)',
          ink: 'var(--ntd-ink, #0F3460)',
          page: 'var(--ntd-page, #f8fafc)',
          card: 'var(--ntd-card, #ffffff)',
          tint: 'var(--ntd-tint, #eff6ff)',
          border: 'var(--ntd-border, #dbeafe)',
        },
        text: {
          DEFAULT: '#112641',
          sub: '#475569',
          muted: '#6B7280',
          disabled: '#9CA3AF',
          inverse: '#FFFFFF',
        },
        border: {
          DEFAULT: '#D8EAF5',
          soft: '#E8F2F8',
          strong: '#B8DFF2',
          dark: '#005B96',
        },
        state: {
          info: '#1784DA',
          infoBg: '#EEF7FF',
          success: '#10B981',
          successBg: '#ECFDF5',
          successText: '#065F46',
          warning: '#F59E0B',
          warningBg: '#FEF3C7',
          warningText: '#92400E',
          error: '#E31D1C',
          errorBg: '#FFF1F1',
          errorText: '#9F1239',
          selected: '#1784DA',
          selectedBg: '#EEF7FF',
          selectedText: '#112641',
        },
        semantic: {
          nav: '#112641',
          tabInactive: '#6B7280',
          divider: '#D8EAF5',
          panel: '#F3F8FC',
        },
      },
      borderRadius: {
        none: '0',
        sm: '8px',
        DEFAULT: '14px',
        md: '14px',
        lg: '18px',
        xl: '22px',
        '2xl': '28px',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 16px 42px rgba(17, 38, 65, 0.10)',
        card: '0 10px 28px rgba(17, 38, 65, 0.08)',
        lift: '0 18px 46px rgba(17, 38, 65, 0.12)',
      },
    },
  },
  plugins: [],
};

export default config;
